### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by luser** [jvns/ruby-stacktrace#12]
Hey there! I love the idea of this tool, and was toying with the idea of doing something similar for other languages. I'd love to reuse some of your code, but you don't have a license on it currently. Would you be amenable to adding an open source license so I can reuse it? I spent a little time fiddling yesterday and extracted the "read process memory" bits into a standalone crate (and even added a Windows implementation), so if you add a license I can publish that to crates.io and submit a PR for this project to use it. :)

**Comment by jvns** [comment]
Thanks!
