### ISSUE TITLE
Release new artifact?

### ISSUE THREAD

**Issue by petems** [jvns/ruby-stacktrace#15]
Is it possible to build a new release artifact for 1.0.0?

The 0.0.4 artifact gives me the following error when I try and use it:
````
ruby-stacktrace: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by ruby-stacktrace)
```

Building from master works fine, but it's a pain to have to compile it every time

**Comment by jvns** [comment]
done! https://github.com/jvns/ruby-stacktrace/releases. let us know if it doesn't work!

**Comment by petems** [comment]
@jvns Awesome, yep this works for me on my CentOS 7 VM, thanks for the quick response 😄
