### ISSUE TITLE
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value'

### ISSUE THREAD

**Issue by igs-awilliams** [jvns/ruby-stacktrace#17]
Command attempted: ./ruby-stacktrace top <PID>

Included version of rustc, cargo (build from source) and backtrace.

rustc 1.12.0 (3191fbae9 2016-09-23)
cargo 0.13.0-nightly (109cb7c 2016-08-19)

```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', ../src/libcore/option.rs:326
stack backtrace:
   1:     0x55cb87f26b79 - std::sys::backtrace::tracing::imp::write::h00e948915d1e4c72
   2:     0x55cb87f2bd5c - std::panicking::default_hook::_{{closure}}::h7b8a142818383fb8
   3:     0x55cb87f2b009 - std::panicking::default_hook::h41cf296f654245d7
   4:     0x55cb87f2b698 - std::panicking::rust_panic_with_hook::h4cbd7ca63ce1aee9
   5:     0x55cb87f2b4f2 - std::panicking::begin_panic::h93672d0313d5e8e9
   6:     0x55cb87f2b460 - std::panicking::begin_panic_fmt::hd0daa02942245d81
   7:     0x55cb87f2b3e1 - rust_begin_unwind
   8:     0x55cb87f65f2f - core::panicking::panic_fmt::hbfc935564d134c1b
   9:     0x55cb87f65e5b - core::panicking::panic::hcee64434f097e399
  10:     0x55cb87c5fa36 - _<core..option..Option<T>>::unwrap::h232dd9aa8175ac1c
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/obj/../src/libcore/option.rs:21
  11:     0x55cb87cb65c2 - ruby_stacktrace::get_types::hcd5718c83894e544
                        at /home/sp00k/dev/ruby-stacktrace/src/lib.rs:435
  12:     0x55cb87c3d0d3 - ruby_stacktrace::main::h5a0cd1e21f1b71c5
                        at /home/sp00k/dev/ruby-stacktrace/src/bin/ruby-stacktrace.rs:54
  13:     0x55cb87f33846 - __rust_maybe_catch_panic
  14:     0x55cb87f2a782 - std::rt::lang_start::h53bf99b0829cc03c
  15:     0x55cb87c3dc33 - main
  16:     0x7fd2d25d8f44 - __libc_start_main
  17:     0x55cb87c1d1d8 - <unknown>
  18:                0x0 - <unknown>
```

**Comment by jvns** [comment]
What ruby version are you using?

**Comment by igs-awilliams** [comment]
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]

**Comment by kamalmarhubi** [comment]
Could you paste output of `readelf --sections $RUBY_BINARY`? Want to be sure it has debug info present. (Or just look for `.debug_info`, `.debug_str`, and `.debug_abbrev` sections.

**Comment by igs-awilliams** [comment]
https://gist.github.com/igs-awilliams/ecad59746e9d847c7223f2f998657ebd

Thank you both for your assistance!

**Comment by jvns** [comment]
(if you actually want to work on your ruby performance problem and not help us debug an experimental library, there's always https://github.com/tmm1/stackprof :))

**Comment by kamalmarhubi** [comment]
Could you run this script on your ruby binary, and upload the resulting tgz somewhere?

Script: https://gist.githubusercontent.com/kamalmarhubi/f23bd119f399c94034720ef7865f1dc3/raw/2b5ff8261537b810b079d816314daeb640cdf9d9/dump-debuginfo

**Comment by kamalmarhubi** [comment]
A bit more info: it's possible that your Ruby stores things in a way different from the ones we tested with. With the debug info from your binary, we can test and see if that is indeed the problem.

**Comment by kamalmarhubi** [comment]
@igs-awilliams this has been inactive for a while so I'm closing it. If you do get a chance to run the script I linked, please do reopen it! Real life issues on other people's computers are going to be super useful!
