### ISSUE TITLE
"tot" column over-counts recursive calls

### ISSUE THREAD

**Issue by cben** [jvns/ruby-stacktrace#23]
I suspect a recursive function gets counted several times towards "tot" column?

A simple non-branching recursion, that sleeps ~1/11 of the time inside and sleeps the rest elsewhere:
```
def recurse(depth)
  if depth > 1
    recurse(depth - 1)
  else
    sleep 0.01  # should spend ~9% here
  end
end

depth = ARGV.first.to_i
while true
  recurse(depth)
  sleep 0.1  # spend ~90% outside `recurse`
end
```

WIth `ruby ~/work-recursive.rb 1` (not recursive), `recurse` function takes 10% as expected:
```
 self | tot  | method
 91.0% | 100.0% | <main> : /home/bpaskinc/work-recursive.rb
 9.0% | 9.0% | recurse : /home/bpaskinc/work-recursive.rb
```

WIth `ruby ~/work-recursive.rb 5`, "self" column proves we still spend 10% time inside the function, bu it's clearly counted 5 times towards "tot":
```
 self | tot  | method
 90.0% | 100.0% | <main> : /home/bpaskinc/work-recursive.rb
 10.0% | 50.0% | recurse : /home/bpaskinc/work-recursive.rb
```
With depth 9, it's 90%, with 10 or more it saturates to 100%....

## Bug or feature?

Not sure but I find it unexpected.
Technically that's the precise value of summing *self + children*.
But I care more about total time spent between entering the func and returning from it, without regard to what other code was called inside.  The fact it included same func again shouldn't inflate it IMHO...

**Comment by jvns** [comment]
thanks so much for reporting this! I'd noticed there was something wrong here, but wasn't able to see what exactly it was. I committed a fix and tested it and it looks like it's reporting the `tot` usage for recurse correctly now.

(also apologies for the very late reply!)
