### ISSUE TITLE
Build broken as crate 'obj' missing

### ISSUE THREAD

**Issue by andrewdavidmackenzie** [jvns/ruby-stacktrace#4]
When I try to build I get this:

> \>cargo build
>    Compiling ruby-stacktrace v0.1.0 (file:///Users/andrew/workspace/ruby-stacktrace)
> dwarf.rs:278:16: 278:25 error: failed to resolve. Use of undeclared type or module `obj` [E0433]
> dwarf.rs:278     let file = obj::open(&file_path);
>                             ^~~~~~~~~
> dwarf.rs:278:16: 278:25 help: run `rustc --explain E0433` to see a detailed explanation
> dwarf.rs:280:22: 280:38 error: failed to resolve. Use of undeclared type or module `obj` [E0433]
> dwarf.rs:280     let debug_info = obj::get_section(&file, ".debug_info")
>                                   ^~~~~~~~~~~~~~~~
> dwarf.rs:280:22: 280:38 help: run `rustc --explain E0433` to see a detailed explanation
> dwarf.rs:282:24: 282:40 error: failed to resolve. Use of undeclared type or module `obj` [E0433]
> dwarf.rs:282     let debug_abbrev = obj::get_section(&file, ".debug_abbrev")
>                                     ^~~~~~~~~~~~~~~~
> dwarf.rs:282:24: 282:40 help: run `rustc --explain E0433` to see a detailed explanation
> dwarf.rs:284:21: 284:37 error: failed to resolve. Use of undeclared type or module `obj` [E0433]
> dwarf.rs:284     let debug_str = obj::get_section(&file, ".debug_str")
>                                  ^~~~~~~~~~~~~~~~
> dwarf.rs:284:21: 284:37 help: run `rustc --explain E0433` to see a detailed explanation
> dwarf.rs:287:8: 287:29 error: failed to resolve. Use of undeclared type or module `obj` [E0433]
> dwarf.rs:287     if obj::is_little_endian(&file) {
>                     ^~~~~~~~~~~~~~~~~~~~~
> dwarf.rs:287:8: 287:29 help: run `rustc --explain E0433` to see a detailed explanation
> error: aborting due to 5 previous errors
> error: Could not compile `ruby-stacktrace`.
> 
> To learn more, run the command again with --verbose.

Looks like there is no extern crate and use for the 'obj' crate.... I'm building on Mac OS X 

> \> cargo --version
> cargo 0.11.0-nightly (259324c 2016-05-20)

Not sure if it builds OK on Linux, if so - then not sure how or where it finds that crate.

I searched for a crate called 'obj' that parses object (ELF?) files, but couldn't figure it out.

**Comment by andrewdavidmackenzie** [comment]
Sorry - now I see it's an internal module below - only compiled for linux :-(

**Comment by kamalmarhubi** [comment]
This whole program only works on Linux at the moment. It's not inconceivable to have the functionality on another OS, but at least for now it's tied to ELF and a linux-specific syscall ([`process_vm_readv`](http://man7.org/linux/man-pages/man2/process_vm_readv.2.htmlhttp://man7.org/linux/man-pages/man2/process_vm_readv.2.html)).
